source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'InfinitePagingViewForSwift_Example', :exclusive => true do
  pod "InfinitePagingViewForSwift", :path => "../"
end

target 'InfinitePagingViewForSwift_Tests', :exclusive => true do
  pod "InfinitePagingViewForSwift", :path => "../"

  
end
